#pragma kernel CSMain

float IN_Radius;
StructuredBuffer<float4> IN_FrustumPlanes;
StructuredBuffer<float4x4> IN_Matrices;
AppendStructuredBuffer<float4x4> OUT_CulledMatrices;

//We will only use id.x so reduce y in numthreads to 1
[numthreads(1, 1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    float4x4 transformationMatrix = IN_Matrices[id.x];

    //we extract the position by taking the last line of the colum
    float3 center = mul(transformationMatrix, float4(0, 0, 0, 1));
    
    // Iterate through all of the planes
    for (int i = 0; i < 6; i++)
    {
        float4 plane = IN_FrustumPlanes[i];
        //plane.xyz is the plane normal while plane.w is a translation by that normal form he space origin
        //that means that the plane with w = 0 will go through cooridnates (0,0)
        //dot(plane.xyz, a) is a distance between the plane and the point a
        //the plane and 
        float d = dot(plane.xyz, center) + plane.w;
        if (d <= -IN_Radius)
            return; // outside
    }
    
    

    OUT_CulledMatrices.Append(IN_Matrices[id.x]);
}
   